### PR TITLE
Android updates

### PR DESCRIPTION
**Pull request by magneticflux-**
Same stuff as OpenFTC/OpenFTC-app#16.

### CODE REVIEW

**Comment by Windwoes** [comment]
We can merge from the main OpenFTC repo, no need to duplicate pull requests.

**Comment by magneticflux-** [comment]
@FROGbots-4634 I'm not sure how you plan to go about doing that. Do you intend for the two repositories to have a shared history? Does this one have an upstream repository to the main one?

**Comment by ItsHarper** [comment]
The two repositories do have a shared history. I set things up to make updates as easy as possible. 
On my machine, I have OpenFTC-app set up as a remote for my clone of OpenFTC-app-turbo. I can update the turbo repo from the main repo with a simple merge, [like this one](https://github.com/OpenFTC/OpenFTC-app-turbo/commit/788a8b0604a82952563493804ddebfc57cd3e20b). 

Having them as "forks" in GitHub would make that clearer, but you can't have a fork of your own repository.

**Comment by magneticflux-** [comment]
@NoahAndrews Okay, I guess that makes sense. It's a little unclear though which caused me some confusion. How do plan to resolve the eventual conflicts between the full package and the "turbo" version? I'm sure extracting the Block and OnBot Java required modifications to the other packages, correct?

**Comment by ItsHarper** [comment]
Shouldn't be hard. Whenever the files I modified for the turbo version get changed upstream, I just might have to do a little manual merging, keeping an eye out for `// Modified for turbo` comments.

**Comment by magneticflux-** [comment]
@NoahAndrews Okay, that makes sense.

If OpenFTC/OpenFTC-app#17 were adopted, you could maintain a fully-featured branch as well as a "turbo" branch for the necessary modules. That would make merging and versioning new sources easier in the long run, I believe.

Using JitPack, you could even have the versions depend on different variants, so branches might not even be needed ([example with different library flavors](https://github.com/jitpack-io/android-jitpack-library-example)). Imagine simply referring to the RobotCore dependency as `implementation 'org.openftc:RobotCore:3.4:turbo'` to require the "turbo" RobotCore dependency version 3.4.

**Comment by ItsHarper** [comment]
As explained there, OpenFTC/OpenFTC-app#17 isn't going to happen. It's too important to be able to modify multiple modules with a single PR. If we were to do that though, I like the idea of "turbo" branches for those module repositories, as long as we keep a separate repository for the turbo app itself. But not because it would make merging/versioning easier, it wouldn't. It's just as easy to pull changes from a remote as it is a branch.

**Pull request closed without merging**
